# Generated by Django 5.2.18 on 2026-10-09 05:35

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=32718)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('provisional', models.BooleanField(default=False)),
                ('fuente', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^S\\d{2}-[A-Z]\\d{3}$')])),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('brigada', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_individuo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_comun', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=255, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('condicion_conservacion', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32718)),
                ('altura_total_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dap_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('copa_ns_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('copa_eo_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('co2_almacenado_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('co2_captura_anual_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estado_general', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_copa', models.CharField(blank=True, max_length=255, null=True)),
                ('tronco_danos', models.CharField(blank=True, max_length=255, null=True)),
                ('raices_base', models.CharField(blank=True, max_length=255, null=True)),
                ('interferencia_entorno', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_detalle_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fuente', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('fila_origen', models.PositiveIntegerField(blank=True, null=True)),
                ('demo', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arboles', to='censo.sector')),
            ],
            options={
                'ordering': ['codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fuente', ''), _negated=True), name='arbol_fuente_no_vacia')],
            },
        ),
    ]
